name: Mission Source Verified

on:
  issues:
    types: [opened, closed]

jobs:
  add-srouce:
    if: ${{ github.event.issue.labels.name == 'source request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo '${{ github.event.issue.body }}'
          echo '${{ github.event.issue.title }}'
          echo '${{ github.event.issue.labels }}'
          echo '${{ github.event.issue.user.login }}'
        
