name: Mission Source Verified

on:
  issues:
    types: [locked]

jobs:
  add-srouce:
    if: ${{ github.event.issue.labels.name }} == 'source request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Update mission source
        run: node utils/issueToJson.js ${{ github.event.issue.user.login }} '${{ github.event.issue.body }}'

      - name: Get Result Path
        run: |
          echo "RESULT<<EOF" >> $GITHUB_ENV
          echo "$(cat $(<result-path))" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update Snapshot
        run: node utils/updateSnapshot.js

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          branch: "update-mission/${{ fromJson(env.RESULT).name }}"
          commit-message: "${{ fromJson(env.RESULT).name }} (${{ fromJson(env.RESULT).version }}) by @${{ github.event.issue.user.login }}"
          title: "Update mission source ${{ fromJson(env.RESULT).name }} (${{ fromJson(env.RESULT).version }}) by @${{ github.event.issue.user.login }}"
          body: |
            Update mission source ${{ fromJson(env.RESULT).name }} (${{ fromJson(env.RESULT).version }}) by @${{ github.event.issue.user.login }}.
            This PR is auto-generated by the workflow.
          draft: false
          delete-branch: true
          add-paths: |
            contents/*

  delete-issue:
    needs: add-srouce
    if: ${{ github.event.issue.labels.name }} == 'source request'
    runs-on: ubuntu-latest
    steps:
      - name: Delete Issue
        run: |
          echo "Deleting issue #${{ github.event.issue.number }}"
          gh issue delete ${{ github.event.issue.number }} --confirm
          echo "Issue deleted successfully."
